### ISSUE TITLE
Bug: webpack hangs with ns-dev-webpack 1.4.0+ and this module

### ISSUE THREAD

**Issue by bradmartin** [tobydeh/nativescript-download-progress#15]
### Which platform(s) does your issue occur on?

Android only tested

### Please, provide the following version numbers that your issue occurs with:

- CLI:  6.3.3
- Cross-platform modules: 6.3.2
- Runtime(s): 6.3.1
- Plugin(s): 
```
  "dependencies": {
    "@maxmobility/nativescript-wear-os-comms": "file:../../../@permobil/nativescript/src/plugins/nativescript-wear-os-comms/src",
    "@maxmobility/private-keys": "github:autochair/maxmobility-private-keys#master",
    "@nativescript/core": "file:../../../forked-plugins/nativescript-core-6.3.2-swipe-modals.tgz",
    "@permobil/core": "file:../../../@permobil/core",
    "@permobil/nativescript": "file:../../../@permobil/nativescript",
    "buffer": "~5.2.1",
    "date-fns": "~1.30.1",
    "injection-js": "~2.2.2",
    "lodash": "~4.17.15",
    "nativescript-android-sensors": "~1.5.0",
    "nativescript-animated-circle": "file:../../../forked-plugins/nativescript-animated-circle-1.3.0.tgz",
    "nativescript-appavailability": "~1.3.2",
    "nativescript-auto-fit-text": "file:../../../forked-plugins/nativescript-auto-fit-text-1.0.1.tgz",
    "nativescript-bluetooth": "file:../../../forked-plugins/nativescript-bluetooth",
    "nativescript-download-progress": "~1.3.0",
    "nativescript-localstorage": "~2.0.0",
    "nativescript-ng-ripple": "~3.0.0-beta.1",
    "nativescript-pager": "file:../../../forked-plugins/nativescript-pager-11.0.11.tgz",
    "nativescript-permissions": "~1.3.8",
    "nativescript-sentry": "file:../../../forked-plugins/nativescript-sentry-1.9.1.tgz",
    "nativescript-sqlite": "~2.3.3",
    "nativescript-sqlite-commercial": "github:autochair/nativescript-sqlite-commercial#master",
    "nativescript-sqlite-encrypted": "github:autochair/nativescript-sqlite-encrypted#master",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-themes": "~2.0.1",
    "nativescript-ui-listview": "~8.0.1",
    "nativescript-vibrate": "~2.1.3",
    "nativescript-wear-os": "~2.1.1",
    "reflect-metadata": "~0.1.13"
  },
```

I'm working through this and I've narrowed down the issue to this plugin. Not saying it's at fault since this plugin works fine with ns-dev-webpack `1.3.0` but it will hang at webpack during a build with `ns-dev-webpack 1.4.0+`. Trying to confirm which file might be possible for the hanging. At the moment, I'm not sure.

Confirmed it's this module but removing this specific dependency and then webpack succeeds, re-add the plugin and hangs again.

**Comment by bradmartin** [comment]
I have confirmed it's related to the worker file in this plugin. If I remove the worker file directly from `node_modules` then webpack no longer hangs. I'm looking now to see what changed with dev-webpack that might have introduced this issue.

**Comment by tobydeh** [comment]
Thanks for the detailed report.

Could you please try testing the previous version (1.2.0)

**Comment by bradmartin** [comment]
I believe I tested and same result, but I will do it again and confirm that removing the worker file fixes it or not.

**Comment by bradmartin** [comment]
Okay, did confirm. Deleting the worker file allows webpack to finish. Of course it errors because the worker file cannot be found but it no longer hangs.

```

ERROR in ../node_modules/nativescript-download-progress/download-progress.js
Module not found: Error: Can't resolve './android-worker.js' in '/Users/bradmartin/projects/permobil-client/apps/wear/smartdrive/node_modules/nativescript-download-progress'
 @ ../node_modules/nativescript-download-progress/download-progress.js 14:31-88
 @ ./namespaces/smartdrive-data.ts
 @ . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./app.ts
```

**Comment by bradmartin** [comment]
Was just reminded that we actually have this plugin in a different app and it works fine. The difference between the app is the working is angular, the hanging one is NS Core (vanilla). So it's likely something in the webpack.config differences between angular projects vs. core.

**Comment by tobydeh** [comment]
I've tested on a vanilla + angular, cli: 6.3.3, tns-core-modules: 6.3.2 tns-android: 6.3.1 and cant reproduce the issue.

**Comment by bradmartin** [comment]
Yea I see that now, it's some combination of the deps in the project causing it, just haven't nailed it down. I do know removing the worker file fixes it but obviously it's not the root cause. Odd issue for sure, fun times 😄
