### ISSUE TITLE
Downloader crashes on multiple downloads on Android

### ISSUE THREAD

**Issue by wendt88** [tobydeh/nativescript-download-progress#18]
## tns info:
```
√ Getting NativeScript components versions information...
√ Component nativescript has 6.5.0 version and is up to date.
√ Component tns-core-modules has 6.5.1 version and is up to date.
√ Component tns-android has 6.5.0 version and is up to date.
√ Component tns-ios has 6.5.0 version and is up to date.
```

## code example:
```
async download () {
    try {
        let folder = fs.knownFolders.documents().getFolder('test'),
            fileUrls = new Array(10).fill('https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg');
        await folder.clear();
        for (let i in fileUrls) {
            const download = new DownloadProgress();
            download.addProgressCallback(progress => {
                console.log(`Progress file ${i}:`, progress);
            })
            await download.downloadFile(
                fileUrls[i],
                fs.path.join(folder.path, i + '.jpeg')
            )
                .then(f => {
                    console.log(`Success file ${i}:`, f);
                })
                .catch(e => {
                    console.log(`Error file ${i}:`, e);
                })
        }
    }
    catch (e) {
        console.error(e);
    }
    console.log('Finish!');
}
```

calling the download method, the app crashes after the 2nd file without error, or the app gets frozen.
when I debug it and keep the breakpoint after every file for a few seconds, it works sometimes.

**Comment by wendt88** [comment]
it works fine without [this line](https://github.com/tobydeh/nativescript-download-progress/blob/master/src/android-worker.js#L85)

**Comment by tobydeh** [comment]
I believe this is the same issue as #17, I will publish a fix later today.

**Comment by wendt88** [comment]
it occures not every time (on my emulator or even phone ca in 80% of the cases)

**Comment by tobydeh** [comment]
I ran the test again today and I'm still unable to reproduce the issue. Are you able to setup an example repo?

**Comment by wendt88** [comment]
[here you can find an example](https://github.com/wendt88/download-progress-demo)
just clone and run `tns run android` inside the app click the 'download'-button

**Comment by toby-wollit** [comment]
Thanks, I cloned your demo repository and run the example without any issues.

What version of the android sdk do you have installed?

**Comment by tobydeh** [comment]
Thanks, I cloned your demo repository and run the example without any issues.

What version of the android sdk do you have installed?

**Comment by wendt88** [comment]
with the 29: `tns run android --compileSdk 29`
I added a log inside the app and made a video:
![download-progress-demo](https://user-images.githubusercontent.com/13959976/96612921-a4c06f00-12fe-11eb-817f-610c4cf5e4f9.gif)

**Comment by toby-wollit** [comment]
I managed to cause the issue once and have not been able to replicate it again. 

Could you please set `supressCallJSMethodExceptions: true` to prevent the application crashing and add some logging using the trace module so we can try to find the error.

**Comment by tobydeh** [comment]
I managed to cause the issue once and have not been able to replicate it again.

Could you please set supressCallJSMethodExceptions: true to prevent the application crashing and add some logging using the trace module so we can try to find the error.

**Comment by wendt88** [comment]
I added `"discardUncaughtJsExceptions": true` to my `app/package.json`, [like here](https://docs.nativescript.org/core-concepts/project-structure-app#apppackagejson) right? But get no error.
In debug mode, at least the `com.tns.ErrorReportActivity`-activity should open, but the app crashes without error. it seems more like a out of memory or something like this, not properly a js/code error.

**Comment by tobydeh** [comment]
Please can you try nativescript-download-progress@next

**Comment by wendt88** [comment]
> Please can you try nativescript-download-progress@next
now it crashes on every 3-5th run. before it crashed at 90%, so it is much better, but not safe enough for my use case :/

**Comment by wendt88** [comment]
now i debuged with `Android studio` and before he started to download the last file (before it crashed), i got the followed error inside the `logcat`:

`NativeAlloc concurrent copying GC freed 3625(323KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 2924KB/5848KB, paused 5.726ms total 75.313ms`

is it helpful?

**Comment by toby-wollit** [comment]
Could you please try restructing your code, move the DownloadProgress instantiation outside of the foor loop..

```
await folder.clear();
const download = new DownloadProgress();
for (let i in fileUrls) {
download.addProgressCallback(progress => {})
```

**Comment by tobydeh** [comment]
Could you please try restructuring your code, move the DownloadProgress instantiation outside of the for loop..

```
await folder.clear();
const download = new DownloadProgress();
for (let i in fileUrls) {
download.addProgressCallback(progress => {})
```

**Comment by wendt88** [comment]
now i was able to download 100 files in a row multiple time without crash, thank you very much!
i saw, that i tried already to move it outside the loop in my main repo, without success, so `1.4.2-rc1` seems to fix this issue
