### ISSUE TITLE
Is there a working demo ??

### ISSUE THREAD

**Issue by ebizcoAU** [tobydeh/nativescript-download-progress#22]
rabbi-gordon-audio/src/app/shared/services/lesson-media.service.ts Good starting point

**Comment by ebizcoAU** [comment]
I re

**Comment by ebizcoAU** [comment]
I tried to use nativescript-worker-loader to replicate the problem. 
It has the same problem too.
ERROR in src/app/share/download.service.ts:9:27 - error TS2307: Cannot find module 'nativescript-worker-loader!./workers/android.worker' or its corresponding type declarations.

9 import * as TsWorker from "nativescript-worker-loader!./workers/android.worker";


                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ebizcoAU** [comment]
a hack could make it work by starting from nativescript-worker-loader demo-angular example.

**Comment by ebizcoAU** [comment]
rabbi-gordon-audio/src/app/shared/services/lesson-media.service.ts   Good starting point

**Comment by toby-wollit** [comment]
The demo code can be found in the README and can be used in an angular project.

**Comment by tobydeh** [comment]
The demo code can be found in the README and can be used in an angular project.

**Comment by tobydeh** [comment]
There was an issue with the android worker loader that you may have been experiencing. 

Please try installing version 1.4.1.
