### ISSUE TITLE
Nativescript-download-progress crashes when using with nativescript-vue

### ISSUE THREAD

**Issue by andreMariano90** [tobydeh/nativescript-download-progress#3]
### Which platform(s) does your issue occur on?
- Android
- Android Version 4.4 - Samsung Tab A and Emulator Android 7.1

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.3
- Cross-platform modules: 3.4.1
- Runtime(s): android 3.4.2
- Plugin(s): ^1.0.7

When starting a nativescript-vue application, the application suddenly crashes on Android. The same doesn't happen on iOS. The import code is very much the same as in any other nativescript application:

`import {DownloadProgress} from "nativescript-download-progress";`

only importing The application already crashes.

`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "./android-worker.js", relative to: app//
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6077)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
File: "file:///data/data/br.com.exati.flowup/files/app/app.js, line: 1, column: 188933

StackTrace: 
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 188934
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177715
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177213
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 150155
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 148004
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "./android-worker.js", relative to: app//
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6077)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 188934
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177715
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177213
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 150155
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 148004
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266

	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "./android-worker.js", relative to: app//
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6077)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
File: "file:///data/data/br.com.exati.flowup/files/app/app.js, line: 1, column: 188933

StackTrace: 
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 188934
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177715
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177213
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 150155
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 148004
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "./android-worker.js", relative to: app//
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6077)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 188934
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177715
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 177213
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 150155
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 148004
	Frame: function:'t', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/br.com.exati.flowup/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266

	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:530)
	at com.tns.Runtime.run(Runtime.java:522)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
	... 8 more
`

**Comment by tobydeh** [comment]
Could you try installing the latest version (1.0.9) and see if it solves your issue.

**Comment by andreMariano90** [comment]
Sorry, same error and the logcat logs aren't helping.
I know you don't officially support vue, thanks for the support anyway

**Comment by jiraiya972** [comment]
Check if you have  "nativescript-worker-loader": "~0.8.1" in your devDependencies.

**Comment by 7ammer** [comment]
Try this...
```
var DownloadProgress = require("nativescript-download-progress").DownloadProgress;
var download = new DownloadProgress();
```

I have it running on android and ios.

**Comment by tobydeh** [comment]
Could you paste an example of how you’re using the plugin and your packge.json file?

**Comment by jdavidbakr** [comment]
I'm getting this error after updating to Nativescript 8 - is this plugin still compatible with NS8?
