### ISSUE TITLE
app shuts down and and .mp4 download stops at about 20%

### ISSUE THREAD

**Issue by alereisan** [tobydeh/nativescript-download-progress#7]
Image files download correctly, but mp4 Videos always stop at 20-25% progress and then the app closes...

Nativescript Angular 

![image](https://user-images.githubusercontent.com/14333479/44955848-39b34480-aeba-11e8-9e67-b51dfbc7c770.png)

**Comment by tobydeh** [comment]
I've tested it and mp4 files download ok. How are you serving the mp4 file?

**Comment by alereisan** [comment]
works if i download 1 file at a time.
