### ISSUE TITLE
no headers support 

### ISSUE THREAD

**Issue by acharyaks90** [tobydeh/nativescript-download-progress#8]
no headers support  in  request method 
 downloadFile(url: string, destinationFilePath?: string) have only url and path

**Comment by aaayushsingh** [comment]
for anyone else coming here, you can use this for now

https://github.com/aaayushsingh/nativescript-download-progress

do  `tns plugin add https://github.com/aaayushsingh/nativescript-download-progress`

I will create a PR for this to be added in the main lib. I just need to make sure it doesn't break anything for people upgrading from older version.

**Comment by tobydeh** [comment]
@aaayushsingh thanks, fire a PR over when you get the chance and I'll merge it in.

**Comment by aaayushsingh** [comment]
@tobydeh please test and merge PR  #10
